var message = "Hello TypeScript";
console.log(message);
var id = 1;
var username = "Asif;";
var isActive = true;
var value = null;
var notDefined = undefined;
console.log("id: ", id, "userName: ", username, "isActive: ", isActive, "value: ", value, "notDefined: ", notDefined);
var fullName = "Asif Ali";
var age = 24;
var isLoggedIn = true;
console.log("name: ", fullName, "age: ", age, "isLoggedIn: ", isLoggedIn);
